spring:
  application:
    name: orderms
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: btgpactualdb
      username: admin
      password: 123
